export enum DynamicInputTypeEnum {
  TEXT_BOX = 'TEXT_BOX',
  TEXT_AREA = 'TEXT_AREA',
  NUMBER_BOX = 'NUMBER_BOX',
  RADIO = 'RADIO',
  MULTI_SELECT = 'MULTI_SELECT',
  SINGLE_SELECT = 'SINGLE_SELECT',
  CHECK_LIST = 'CHECK_LIST',
  DATE_PICKER = 'DATE_PICKER',
  TIME_PICKER = 'TIME_PICKER',
  DATETIME_PICKER = 'DATETIME_PICKER',
  EMAIL = 'EMAIL',
  PHONE_NUMBER = 'PHONE_NUMBER',
}
